### ISSUE TITLE
Setup Node.js API with Vite

### ISSUE THREAD

**Issue by Adam-Doria** [Adam-Doria/Antred#3]
**Description :**
 Set up the Node.js backend using Vite for fast development.
**Tasks:**

- [x]  Create a new Node.js project in the apps/api directory.
- [x]  Set up Vite for the backend.
- [x]  Configure TypeScript support.
- [x]  Install and configure ESLint

**Comment by Adam-Doria** [comment]
Plan change go for Ts-node.
