### ISSUE TITLE
Configure Supabase for Database and Authentication

### ISSUE THREAD

**Issue by Adam-Doria** [Adam-Doria/Antred#4]
**Description :**
 Set up Supabase for managing the database and authentication.
**Tasks:**

- [ ]  Set up a Supabase project.
- [ ]  Create tables and configure schemas for users and missing persons.
- [ ]  Set up Supabase authentication.
- [ ]  Configure environment variables for Supabase connection in both frontend and backend.
